// Auto-generated by panel_generator.py — do not edit
window.STATE_FLOW_DIAGRAM = `flowchart TD
    S0["0 · Introduction\\nUser reads intro text"]
    S1["1 · Happy Memory\\nUser interacts with young Pengy"]
    S2["2 · Aging Transition\\nUser watches a cinematic"]
    S3["3 · Start Screen\\nUser reads instructions"]
    S4["4 · Main Game - Calm\\nUser is waiting"]
    S5["5 · Main Game - Uncomfortable\\nUser must solve a need"]
    S6["6 · Main Game - Needs Hug\\nUser must hug penguin"]
    S7["7 · Main Game - Holding Item\\nUser holds an item"]
    S8["8 · End Screen\\nUser reads outcome"]

    classDef s0style fill:#2a2926,stroke:#2c3e50,stroke-width:2px,color:#ffffff
    classDef s1style fill:#1a2930,stroke:#2c3e50,stroke-width:2px,color:#ffffff
    classDef s2style fill:#1a2930,stroke:#2c3e50,stroke-width:2px,color:#ffffff
    classDef s3style fill:#2a2926,stroke:#2c3e50,stroke-width:2px,color:#ffffff
    classDef s4style fill:#2a2926,stroke:#000000,stroke-width:2px,color:#ffffff
    classDef s5style fill:#2a2926,stroke:#000000,stroke-width:2px,color:#ffffff
    classDef s6style fill:#330000,stroke:#000000,stroke-width:2px,color:#ffffff
    classDef s7style fill:#2a2926,stroke:#000000,stroke-width:2px,color:#ffffff
    classDef s8style fill:#2a2926,stroke:#8b4513,stroke-width:2px,color:#ffffff
    classDef active stroke:#ffffff,stroke-width:4px,filter:url(#glow)

    class S0 s0style
    class S1 s1style
    class S2 s2style
    class S3 s3style
    class S4 s4style
    class S5 s5style
    class S6 s6style
    class S7 s7style
    class S8 s8style`;

// Render diagram on first call
var _mermaidRendered = false;
window.renderMermaidDiagram = function() {
    if (_mermaidRendered || typeof mermaid === 'undefined') return;
    var el = document.getElementById('stateFlowMermaid');
    if (el && window.STATE_FLOW_DIAGRAM) {
        el.textContent = window.STATE_FLOW_DIAGRAM;
        mermaid.run({ nodes: [el] });
        _mermaidRendered = true;
    }
};
