// state_jumper.js — generated by AI State Analyzer
// AI-generated jump codes for state navigation. Do not edit manually.
// Regenerate: python generate_state_panel.py <your-file.html>
//
// HOW TO USE:
//   1. Open index_with_panel.html in your browser (via dev server)
//   2. Open DevTools console (F12)
//   3. Paste this line and press Enter:
//        var s=document.createElement('script');s.src='state_jumper.js';document.body.appendChild(s);
//   4. "Jump" buttons will appear on each state card in the panel

(function () {
    // ── 1. Inject CSS ──────────────────────────────────────────────────────────
    var style = document.createElement('style');
    style.textContent = [
        '.jump-btn { background: rgba(155,89,182,0.2); color: rgba(200,150,255,0.9); border: 1px solid rgba(155,89,182,0.5); padding: 4px 10px; border-radius: 12px; font-size: 10px; font-weight: 600; cursor: pointer; transition: all 0.3s ease; text-transform: uppercase; letter-spacing: 0.5px; margin-left: 2px; }',
        '.jump-btn:hover { background: rgba(155,89,182,0.4); border-color: rgba(155,89,182,0.8); transform: scale(1.05); box-shadow: 0 0 8px rgba(155,89,182,0.4); }',
        '.jump-btn:active { transform: scale(0.95); }',
        '.jump-btn.jumping { background: rgba(241,196,15,0.3); border-color: rgba(241,196,15,0.7); color: rgba(241,196,15,0.9); cursor: not-allowed; }',
        '.jump-btn.jump-success { background: rgba(46,204,113,0.3); border-color: rgba(46,204,113,0.7); color: rgba(46,204,113,0.9); }',
        '.jump-btn.jump-error { background: rgba(231,76,60,0.3); border-color: rgba(231,76,60,0.7); color: rgba(231,76,60,0.9); }'
    ].join('\n');
    document.head.appendChild(style);

    // ── 2. AI jump transition data ────────────────────────────────────────────
    var stateJumpTransitions = {};

    // ── 3. AI jump setup (one-time init, if any) ──────────────────────────────
    (function () {
        
    })();

    // ── 4. Inject Jump buttons into each state card ───────────────────────────
    function injectButtons() {
        document.querySelectorAll('.stage-segment').forEach(function (card) {
            var match = card.id && card.id.match(/^state(\d+)$/);
            if (!match) return;
            var stateId = parseInt(match[1]);
            var btnGroup = card.querySelector('.stage-header > div');
            if (!btnGroup || btnGroup.querySelector('.jump-btn')) return;
            var btn = document.createElement('button');
            btn.className = 'jump-btn';
            btn.id = 'jumpBtn' + stateId;
            btn.textContent = 'Jump';
            btn.title = 'Jump to this state from current state';
            btn.onclick = (function (id) { return function () { jumpToState(id); }; })(stateId);
            btnGroup.appendChild(btn);
        });
    }

    // ── 5. Core jump logic ────────────────────────────────────────────────────
    window.jumpToState = function (targetStateId) {
        var fromStateId = (typeof getCurrentState === 'function') ? getCurrentState() : -1;
        var key = fromStateId + '_' + targetStateId;
        var transition = stateJumpTransitions[key];
        var btn = document.getElementById('jumpBtn' + targetStateId);

        if (!transition || !transition.code) {
            if (btn) {
                btn.classList.add('jump-error');
                btn.textContent = (fromStateId === targetStateId) ? 'Here!' : 'No path';
                setTimeout(function () { btn.classList.remove('jump-error'); btn.textContent = 'Jump'; }, 1500);
            }
            console.warn('[Jump] No transition code for ' + fromStateId + ' \u2192 ' + targetStateId +
                '. Available: ' + Object.keys(stateJumpTransitions).join(', '));
            return;
        }

        document.querySelectorAll('.jump-btn').forEach(function (b) { b.disabled = true; });
        if (btn) { btn.classList.add('jumping'); btn.textContent = 'Jumping\u2026'; }

        console.log(
            '%c[Jump] State ' + fromStateId + ' \u2192 State ' + targetStateId +
            ' (confidence: ' + Math.round((transition.confidence || 0) * 100) + '%' +
            (transition.notes ? ' \u2014 ' + transition.notes : '') + ')',
            'color:#9b59b6;font-weight:bold'
        );

        setTimeout(function () {
            try {
                (new Function(transition.code))();
            } catch (e) {
                console.error('[Jump] Execution error:', e);
                _jumpFinalize(btn, targetStateId, false);
                return;
            }
            setTimeout(function () {
                if (typeof debouncedUpdate === 'function') debouncedUpdate();
                if (typeof updateStateHighlight === 'function') setTimeout(updateStateHighlight, 500);
                _jumpFinalize(btn, targetStateId, true);
            }, 300);
        }, 20);
    };

    function _jumpFinalize(btn, stateId, success) {
        document.querySelectorAll('.jump-btn').forEach(function (b) {
            b.disabled = false;
            b.classList.remove('jumping');
        });
        if (!btn) return;
        btn.classList.add(success ? 'jump-success' : 'jump-error');
        btn.textContent = success ? 'Jumped!' : 'Failed';
        setTimeout(function () {
            btn.classList.remove('jump-success', 'jump-error');
            btn.textContent = 'Jump';
        }, 1500);
        if (success) {
            var card = document.getElementById('state' + stateId);
            if (card) card.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }

    // ── 6. Initialize ─────────────────────────────────────────────────────────
    injectButtons();
    var n = Object.keys(stateJumpTransitions).length;
    console.log(
        '%c[StateJumper] Loaded \u2014 ' + n + ' jump transition' + (n === 1 ? '' : 's') + ' available',
        'color:#9b59b6;font-weight:bold;font-size:13px'
    );
    if (n === 0) {
        console.warn('[StateJumper] No transitions found. Re-run the analyzer to generate jump codes.');
    }
})();
