// Auto-generated by panel_generator.py — do not edit
window.STATE_FLOW_DIAGRAM = `flowchart TD
    S0["0 · Welcome Screen<br/>Entry point to experience"]
    S1["1 · Warm Notifications<br/>Gentle notifications phase"]
    S2["2 · Transition 1-3<br/>First escalation gate"]
    S3["3 · Stress Phase<br/>Anxiety notifications"]
    S4["4 · Transition 3-5<br/>Second escalation gate"]
    S5["5 · Intense Phase<br/>Rapid addictive notifications"]
    S6["6 · Transition 5-7<br/>Final escalation gate"]
    S7["7 · Hell Mode<br/>Notifications escape phone"]
    S8["8 · Trap Screen<br/>Prevents exit"]
    S9["9 · Flood Overlay<br/>Existential message"]
    S10["10 · Game Over<br/>Social capital lost"]
    S11["11 · Reflection Overlay<br/>Engagement profile shown"]

    S0 -->|"User clicks Open Instagram"| S1
    S1 -.->|"⚡ 15 notifications reached"| S2
    S2 -->|"User chooses to continue"| S3
    S2 -->|"User tries to stop"| S8
    S3 -.->|"⚡ 50 notifications reached"| S4
    S4 -->|"User chooses to continue"| S5
    S4 -->|"User tries to stop"| S8
    S5 -.->|"⚡ 100 notifications reached"| S6
    S6 -->|"User chooses to continue"| S7
    S6 -->|"User tries to stop"| S8
    S7 -.->|"⚡ 150 notifications reached"| S9
    S8 -->|"User gives in to trap"| S3
    S8 -->|"User gives in to trap"| S5
    S8 -->|"User gives in to trap"| S7
    S8 -->|"User dodges trap button"| S10
    S10 -->|"User restarts experience"| S0
    S1 -->|"User taps reflection notif"| S11
    S11 -->|"User closes reflection"| S1

    classDef s0style fill:#2a1a1e,stroke:#ff6b6b
    classDef s1style fill:#2a1a1e,stroke:#ffb6c1
    classDef s2style fill:#1e1a2a,stroke:#c44dff
    classDef s3style fill:#1e1a20,stroke:#8c64a0
    classDef s4style fill:#1e1a2a,stroke:#c44dff
    classDef s5style fill:#2a1a1e,stroke:#ff0000
    classDef s6style fill:#1e1a2a,stroke:#c44dff
    classDef s7style fill:#820000,stroke:#ff3200
    classDef s8style fill:#1e1a2a,stroke:#6450ff
    classDef s9style fill:#8b0000,stroke:#8b0000
    classDef s10style fill:#000000,stroke:#ffffff
    classDef s11style fill:#2a2520,stroke:#ffc864

    class S0 s0style
    class S1 s1style
    class S2 s2style
    class S3 s3style
    class S4 s4style
    class S5 s5style
    class S6 s6style
    class S7 s7style
    class S8 s8style
    class S9 s9style
    class S10 s10style
    class S11 s11style`;

// Render diagram on first call
var _mermaidRendered = false;
window.renderMermaidDiagram = function() {
    if (_mermaidRendered || typeof mermaid === 'undefined') return;
    var el = document.getElementById('stateFlowMermaid');
    if (el && window.STATE_FLOW_DIAGRAM) {
        el.textContent = window.STATE_FLOW_DIAGRAM;
        mermaid.run({ nodes: [el] });
        _mermaidRendered = true;
    }
};
