// Auto-generated by panel_generator.py — do not edit
window.STATE_FLOW_DIAGRAM = `flowchart TD
    S0["0 · Welcome Screen\\nentry point to experience"]
    S1["1 · Warm Notifications\\nwarm engagement phase"]
    S2["2 · Transition 1-3\\nfirst escalation gate"]
    S3["3 · Stress Phase\\nstress escalation"]
    S4["4 · Trap Screen\\ninfinite prevention system"]
    S5["5 · Transition 3-6\\nsecond escalation gate"]
    S6["6 · Intense Phase\\nintense bombardment"]
    S7["7 · Transition 6-8\\nfinal escalation gate"]
    S8["8 · Hell Mode\\nnotifications escape screen"]
    S9["9 · Flood Overlay\\nexistential crisis screen"]
    S10["10 · Game Over\\nsocial capital depleted"]
    S11["11 · Reflection Easter Egg\\nengagement profile reveal"]

    S0 -->|"User clicks Open Instagram"| S1
    S1 -.->|"⚡ 15 notifications reached"| S2
    S2 -->|"User chooses to continue"| S3
    S2 -->|"User tries to stop"| S4
    S3 -.->|"⚡ 50 notifications reached"| S5
    S4 -->|"User accepts trap offer"| S2
    S4 -->|"User dodges trap 8+ times"| S10
    S5 -->|"User continues to intense"| S6
    S5 -->|"User tries to stop again"| S4
    S6 -.->|"⚡ 100 notifications reached"| S7
    S7 -->|"User enters hell mode"| S8
    S7 -->|"User final attempt to stop"| S4
    S8 -.->|"⚡ 150 notifications reached"| S9
    S10 -->|"User restarts experience"| S0

    classDef s0style fill:#2a1a1e,stroke:#ff8fab
    classDef s1style fill:#2a1a1e,stroke:#ffb6c1
    classDef s2style fill:#1e0f2a,stroke:#c44dff
    classDef s3style fill:#1a1520,stroke:#8c64a0
    classDef s4style fill:#0f0d2a,stroke:#6450ff
    classDef s5style fill:#1e0f2a,stroke:#c44dff
    classDef s6style fill:#2a0d0d,stroke:#ff4444
    classDef s7style fill:#1e0f2a,stroke:#c44dff
    classDef s8style fill:#1a0000,stroke:#ff3200
    classDef s9style fill:#1a0000,stroke:#8b0000
    classDef s10style fill:#000000,stroke:#ffffff
    classDef s11style fill:#2a2010,stroke:#ffd764

    class S0 s0style
    class S1 s1style
    class S2 s2style
    class S3 s3style
    class S4 s4style
    class S5 s5style
    class S6 s6style
    class S7 s7style
    class S8 s8style
    class S9 s9style
    class S10 s10style
    class S11 s11style`;

// Render diagram on first call
var _mermaidRendered = false;
window.renderMermaidDiagram = function() {
    if (_mermaidRendered || typeof mermaid === 'undefined') return;
    var el = document.getElementById('stateFlowMermaid');
    if (el && window.STATE_FLOW_DIAGRAM) {
        el.textContent = window.STATE_FLOW_DIAGRAM;
        mermaid.run({ nodes: [el] });
        _mermaidRendered = true;
    }
};

// Highlight active state node in the SVG
window.updateMermaidHighlight = function(currentState) {
    document.querySelectorAll('.mermaid-node-active').forEach(function(el) {
        el.classList.remove('mermaid-node-active');
    });
    var activeNode = document.querySelector('[id^="flowchart-S' + currentState + '-"]');
    if (activeNode) {
        activeNode.classList.add('mermaid-node-active');
    }
};
