// state_jumper.js — generated by AI State Analyzer
// AI-generated jump codes for state navigation. Do not edit manually.
// Regenerate: python generate_state_panel.py <your-file.html>
//
// HOW TO USE:
//   1. Open index_with_panel.html in your browser (via dev server)
//   2. Open DevTools console (F12)
//   3. Paste this line and press Enter:
//        var s=document.createElement('script');s.src='jump-states/state_jumper.js';document.body.appendChild(s);
//   4. "Jump" buttons will appear on each state card in the panel

(function () {
    // ── 1. Inject CSS ──────────────────────────────────────────────────────────
    var style = document.createElement('style');
    style.textContent = [
        '.jump-btn { background: rgba(155,89,182,0.2); color: rgba(200,150,255,0.9); border: 1px solid rgba(155,89,182,0.5); padding: 4px 10px; border-radius: 12px; font-size: 10px; font-weight: 600; cursor: pointer; transition: all 0.3s ease; text-transform: uppercase; letter-spacing: 0.5px; margin-left: 2px; }',
        '.jump-btn:hover { background: rgba(155,89,182,0.4); border-color: rgba(155,89,182,0.8); transform: scale(1.05); box-shadow: 0 0 8px rgba(155,89,182,0.4); }',
        '.jump-btn:active { transform: scale(0.95); }',
        '.jump-btn.jumping { background: rgba(241,196,15,0.3); border-color: rgba(241,196,15,0.7); color: rgba(241,196,15,0.9); cursor: not-allowed; }',
        '.jump-btn.jump-success { background: rgba(46,204,113,0.3); border-color: rgba(46,204,113,0.7); color: rgba(46,204,113,0.9); }',
        '.jump-btn.jump-error { background: rgba(231,76,60,0.3); border-color: rgba(231,76,60,0.7); color: rgba(231,76,60,0.9); }'
    ].join('\n');
    document.head.appendChild(style);

    // ── 2. AI jump transition data ────────────────────────────────────────────
    var stateJumpTransitions = {
  "0_1": {
    "code": "startHell();",
    "confidence": 0.99,
    "notes": "Calls the standard function to begin Stage 1."
  },
  "0_2": {
    "code": "startHell();\nnotificationCount = 15;\nstage = 2;\nclearAllTimers();\nstartStage2();",
    "confidence": 0.95,
    "notes": "Initializes the UI, sets state variables to the start of Stage 2, clears the Stage 1 timer, and calls the Stage 2 initializer."
  },
  "0_3": {
    "code": "startHell();\nnotificationCount = 50;\nstage = 3;\nclearAllTimers();\nstartStage2();\nclearAllTimers();\nstartStage3();",
    "confidence": 0.95,
    "notes": "Chains initializers, using startStage2() to set the required UI theme before clearing its timer and starting Stage 3."
  },
  "0_4": {
    "code": "startHell();\nnotificationCount = 100;\nstage = 4;\nclearAllTimers();\nstartStage2();\nclearAllTimers();\nstartHell4();",
    "confidence": 0.95,
    "notes": "Sets up the UI for the stress phase, then clears timers and immediately jumps into Hell Mode logic."
  },
  "0_5": {
    "code": "startHell();\nnotificationCount = 15;\nstage = 2;\nclearAllTimers();\nshowTransitionScreen('stage1to2', startStage2);",
    "confidence": 0.95,
    "notes": "Sets the state to the threshold of Stage 2 and directly calls the function to show the corresponding transition screen."
  },
  "0_6": {
    "code": "startHell();\nnotificationCount = 50;\nstage = 3;\nclearAllTimers();\nstartStage2();\nclearAllTimers();\nshowTransitionScreen('stage2to3', startStage3);",
    "confidence": 0.95,
    "notes": "Sets up the Stage 2 UI, advances the state to the Stage 3 threshold, and shows the transition screen."
  },
  "0_7": {
    "code": "startHell();\nnotificationCount = 100;\nstage = 4;\nclearAllTimers();\nstartStage2();\nclearAllTimers();\nstartStage3();\nclearAllTimers();\nshowTransitionScreen('stage3to4', startHell4);",
    "confidence": 0.95,
    "notes": "Progresses the app state to the Stage 4 threshold and shows the final transition screen before Hell Mode."
  },
  "0_8": {
    "code": "startHell();\nclearAllTimers();\npendingNextStageCallback = startStage2;\ntrapDodgeCount = 0;\nshowTrapScreen();",
    "confidence": 0.95,
    "notes": "Initializes a base UI, clears timers, and directly shows the trap screen with a default callback for the 'Yes' button."
  },
  "0_9": {
    "code": "startHell();\nclearAllTimers();\nshowReflectionOverlay();",
    "confidence": 0.95,
    "notes": "Sets up the warm Stage 1 UI for visual context, stops the notification timer, and directly displays the easter egg overlay."
  },
  "0_10": {
    "code": "startHell();\nnotificationCount = 150;\nstage = 4;\nisHellMode = true;\nclearAllTimers();\nstartStage2();\nclearAllTimers();\ndocument.getElementById('floodOverlay').style.display = 'flex';",
    "confidence": 0.95,
    "notes": "Sets all necessary state variables for the end of Hell Mode and directly displays the final flood overlay."
  },
  "0_11": {
    "code": "notificationCount = 40;\ntapCount = 20;\nshowGameOver();",
    "confidence": 0.99,
    "notes": "Sets plausible stats for the score calculation and directly calls the function to show the Game Over screen."
  },
  "1_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "2_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "3_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "4_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "5_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "6_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "7_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "8_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "9_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "10_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  },
  "11_0": {
    "code": "clearAllTimers();\nrestartExperience();",
    "confidence": 0.99,
    "notes": "Clears all timers and calls the built-in reset function, which reliably returns the app to its initial state."
  }
};

    // ── 3. AI jump setup (one-time init, if any) ──────────────────────────────
    (function () {
        window.activeTimers = [];
const originalSetInterval = window.setInterval;
const originalSetTimeout = window.setTimeout;
const originalClearInterval = window.clearInterval;
const originalClearTimeout = window.clearTimeout;

window.setInterval = function(callback, delay) {
    const id = originalSetInterval(callback, delay);
    window.activeTimers.push({ id: id, type: 'interval' });
    return id;
};

window.setTimeout = function(callback, delay) {
    const id = originalSetTimeout(callback, delay);
    window.activeTimers.push({ id: id, type: 'timeout' });
    return id;
};

window.clearInterval = function(id) {
    originalClearInterval(id);
    window.activeTimers = window.activeTimers.filter(t => t.id !== id);
};

window.clearTimeout = function(id) {
    originalClearTimeout(id);
    window.activeTimers = window.activeTimers.filter(t => t.id !== id);
};

window.clearAllTimers = function() {
    window.activeTimers.forEach(timer => {
        if (timer.type === 'interval') {
            originalClearInterval(timer.id);
        } else {
            originalClearTimeout(timer.id);
        }
    });
    window.activeTimers = [];
    if (window.urgentTimers) {
        window.urgentTimers.forEach(id => originalClearInterval(id));
        window.urgentTimers = [];
    }
};

window.hideAllOverlays = function() {
    document.getElementById('transitionOverlay').classList.remove('visible');
    document.getElementById('trapOverlay').classList.remove('visible');
    document.getElementById('reflectionOverlay').classList.remove('visible');
    document.getElementById('gameoverOverlay').classList.remove('visible');
    document.getElementById('floodOverlay').style.display = 'none';
};
    })();

    // ── 4. Inject Jump buttons into each state card ───────────────────────────
    function injectButtons() {
        document.querySelectorAll('.stage-segment').forEach(function (card) {
            var match = card.id && card.id.match(/^state(\d+)$/);
            if (!match) return;
            var stateId = parseInt(match[1]);
            var btnGroup = card.querySelector('.stage-header > div');
            if (!btnGroup || btnGroup.querySelector('.jump-btn')) return;
            var btn = document.createElement('button');
            btn.className = 'jump-btn';
            btn.id = 'jumpBtn' + stateId;
            btn.textContent = 'Jump';
            btn.title = 'Jump to this state from current state';
            btn.onclick = (function (id) { return function () { jumpToState(id); }; })(stateId);
            btnGroup.appendChild(btn);
        });
    }

    // ── 5. Core jump logic ────────────────────────────────────────────────────
    window.jumpToState = function (targetStateId) {
        var fromStateId = (typeof getCurrentState === 'function') ? getCurrentState() : -1;
        var key = fromStateId + '_' + targetStateId;
        var transition = stateJumpTransitions[key];
        var btn = document.getElementById('jumpBtn' + targetStateId);

        // Hub-and-spoke fallback: chain through state 0 if no direct path
        if ((!transition || !transition.code) && fromStateId !== 0 && targetStateId !== 0) {
            var toHub = stateJumpTransitions[fromStateId + '_0'];
            var fromHub = stateJumpTransitions['0_' + targetStateId];
            if (toHub && toHub.code && fromHub && fromHub.code) {
                transition = {
                    code: toHub.code + ';\n' + fromHub.code,
                    confidence: Math.min(toHub.confidence || 0, fromHub.confidence || 0),
                    notes: 'chained via state 0'
                };
            }
        }

        if (!transition || !transition.code) {
            if (btn) {
                btn.classList.add('jump-error');
                btn.textContent = (fromStateId === targetStateId) ? 'Here!' : 'No path';
                setTimeout(function () { btn.classList.remove('jump-error'); btn.textContent = 'Jump'; }, 1500);
            }
            console.warn('[Jump] No transition code for ' + fromStateId + ' \u2192 ' + targetStateId +
                '. Available: ' + Object.keys(stateJumpTransitions).join(', '));
            return;
        }

        document.querySelectorAll('.jump-btn').forEach(function (b) { b.disabled = true; });
        if (btn) { btn.classList.add('jumping'); btn.textContent = 'Jumping\u2026'; }

        console.log(
            '%c[Jump] State ' + fromStateId + ' \u2192 State ' + targetStateId +
            ' (confidence: ' + Math.round((transition.confidence || 0) * 100) + '%' +
            (transition.notes ? ' \u2014 ' + transition.notes : '') + ')',
            'color:#9b59b6;font-weight:bold'
        );

        setTimeout(function () {
            try {
                (new Function(transition.code))();
            } catch (e) {
                console.error('[Jump] Execution error:', e);
                _jumpFinalize(btn, targetStateId, false);
                return;
            }
            setTimeout(function () {
                if (typeof debouncedUpdate === 'function') debouncedUpdate();
                if (typeof updateStateHighlight === 'function') setTimeout(updateStateHighlight, 500);
                _jumpFinalize(btn, targetStateId, true);
            }, 300);
        }, 20);
    };

    function _jumpFinalize(btn, stateId, success) {
        document.querySelectorAll('.jump-btn').forEach(function (b) {
            b.disabled = false;
            b.classList.remove('jumping');
        });
        if (!btn) return;
        btn.classList.add(success ? 'jump-success' : 'jump-error');
        btn.textContent = success ? 'Jumped!' : 'Failed';
        setTimeout(function () {
            btn.classList.remove('jump-success', 'jump-error');
            btn.textContent = 'Jump';
        }, 1500);
        if (success) {
            var card = document.getElementById('state' + stateId);
            if (card) card.scrollIntoView({ behavior: 'smooth', block: 'center' });
        }
    }

    // ── 6. Initialize ─────────────────────────────────────────────────────────
    injectButtons();
    var n = Object.keys(stateJumpTransitions).length;
    console.log(
        '%c[StateJumper] Loaded \u2014 ' + n + ' jump transition' + (n === 1 ? '' : 's') + ' available',
        'color:#9b59b6;font-weight:bold;font-size:13px'
    );
    if (n === 0) {
        console.warn('[StateJumper] No transitions found. Re-run the analyzer to generate jump codes.');
    }
})();
